version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_INIT_USERNAME=admin
      - INFLUXDB_INIT_PASSWORD=ChangeThisInflux!
      - INFLUXDB_INIT_ORG=MDX
      - INFLUXDB_INIT_BUCKET=Prison_Data
      - INFLUXDB_INIT_ADMIN_TOKEN=REPLACE_WITH_REAL_TOKEN
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - internal

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./certs/mosquitto:/mosquitto/certs:ro
      - mosquitto-data:/mosquitto/data
    networks:
      - internal

  edge:
    build:
      context: ../edge
      dockerfile: Dockerfile.pi
    container_name: edge
    restart: unless-stopped
    depends_on:
      - influxdb
      - mosquitto
    environment:
      - CONFIG_PATH=/app/config.yaml
    ports:
      - "5000:5000"
    volumes:
      - ../edge/config.yaml:/app/config.yaml:ro
      - ../edge/models:/app/models:rw
      - ../certs/edge:/app/certs:ro
      - edge-logs:/app/logs
    networks:
      - internal

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - ../certs/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - edge
    networks:
      - internal

volumes:
  influxdb-data:
  mosquitto-data:
  edge-logs:

networks:
  internal:
    driver: bridge
